apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask_app
spec:
  type: NodePort
  selector:
    app: flask_app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
