version: '3'
services:
  registry:
    image: registry:2
    restart: on-failure
    ports:
      - 5000:5000
    environment:
      - REGISTRY_ENV=development
      - PYTHONUNBUFFERED=True
    volumes:
      - .:/registry

  flask_app:
    build: .
    container_name: flask_app
    image: flask_app:2
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    volumes:
      - .:/flask_app
